extends:
  - eslint:recommended

env:
  node: true

rules:
  indent: ['error', 2]
  no-console: 'off'
  strict: ['error', 'global']
  sort-vars: 'error'
  space-infix-ops: 'error'
  no-negated-condition: 'error'
  yoda: 'error'
  no-else-return: 'error'
  max-len: ['error', 80]
  semi: 'error'
  dot-notation: 'error'
  eqeqeq: 'error'
  no-multi-spaces: 'error'
  no-unmodified-loop-condition: 'error'
  no-unreachable: 'error'
  id-blacklist: ['error', /*Objg/]
